# Generated by Django 3.1 on 2020-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200817_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='category_product/')),
            ],
        ),
        migrations.CreateModel(
            name='Collapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='collapse/')),
            ],
        ),
    ]
