# Generated by Django 3.1 on 2020-08-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_categoryproduct_collapse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collapse',
            new_name='Slide',
        ),
    ]
