# Generated by Django 3.1 on 2020-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200825_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_qty',
            field=models.IntegerField(default=1),
        ),
    ]
