# Generated by Django 3.1 on 2020-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_max_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
