# Generated by Django 3.1 on 2020-09-03 20:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200813_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='2', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
